---
- name: Send consolidated VM report for all environments
  hosts: localhost
  gather_facts: true
  vars:
    collected_metrics: >-
      {{
        hostvars |
        dict2items |
        selectattr('value.vm_metrics', 'defined') |
        map(attribute='value.vm_metrics') |
        list
      }}
    dev_metrics: >-
      {{
        collected_metrics |
        selectattr('environment', 'defined') |
        selectattr('environment', 'equalto', 'dev') |
        list
      }}
    prod_metrics: >-
      {{
        collected_metrics |
        selectattr('environment', 'defined') |
        selectattr('environment', 'equalto', 'prod') |
        list
      }}
    qqa_metrics: >-
      {{
        collected_metrics |
        selectattr('environment', 'defined') |
        selectattr('environment', 'equalto', 'qqa') |
        list
      }}
    timestamp: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
    subject_line: "📊 Multi-Environment VM Report – {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
  tasks:
    - name: Send HTML report via email
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ email_user }}"
        password: "{{ email_pass }}"
        to: "{{ alert_recipient }}"
        subject: "{{ subject_line }}"
        body: "{{ lookup('template', 'templates/report_email_multi_env.html.j2') }}"
        subtype: html