plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
filters:
  tag:Role: web
  instance-state-name: running
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Name
    prefix: name
  - key: tags.Environment
    prefix: env
  - key: tags.Role
    prefix: role